# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

# Linux testing 
pool:
  vmImage: 'ubuntu-latest'

steps:
# Install requirements
- script: pip install pylint
  displayName: 'Install requirements'

# Lint Check
- script: pylint
  displayName: 'Style Check'

# Run unit Tests on Python version 2.x
- script: |
    echo Running tests
    echo Display test results
  displayName: 'Running Tests'
